import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "ActivityOverlays Terms of Service",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white text-[#111111]">
      <div className="mx-auto w-full max-w-3xl px-6 pt-6">
        <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-[#6B6B6B] hover:text-[#111111] transition-colors">
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back
        </Link>
      </div>
      <article className="mx-auto w-full max-w-3xl space-y-8 px-6 py-8">
        <header className="space-y-2">
          <h1 className="text-3xl font-extrabold text-[#111111]">Terms of Service</h1>
          <p className="text-sm text-[#6B6B6B]">Last updated: April 8, 2026</p>
        </header>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#111111]">1. Service Description</h2>
          <p>
            ActivityOverlays is a Strava-integrated application that provides route visualization and analytics for
            athlete activity data.
          </p>
          <p>
            The service is intended to help you visualize your own data and create exports for your own use. You are
            responsible for how you use outputs generated by the service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#111111]">2. Strava Relationship Disclaimer</h2>
          <p>
            ActivityOverlays is powered by the Strava API but is not endorsed by, sponsored by, or affiliated with
            Strava beyond API usage rights.
          </p>
          <p>
            The Strava name and logos belong to Strava and are used only to comply with branding and attribution
            requirements.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#111111]">3. Account Connection</h2>
          <p>
            To use Strava-powered features, you must authorize access through Strava OAuth. You are responsible
            for maintaining the security of your Strava account.
          </p>
          <p>
            You agree to provide accurate information, use the service only for lawful purposes, and avoid
            attempting to bypass limits, restrictions, or security measures.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#111111]">4. Acceptable Use</h2>
          <ul className="list-disc space-y-1 pl-6">
            <li>Use the service for unlawful activities</li>
            <li>Attempt to reverse engineer, disrupt, or abuse the platform</li>
            <li>Use automated methods that violate API or system limits</li>
            <li>Misrepresent the service as an official Strava product</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#111111]">5. Data and Privacy</h2>
          <p>Your use of ActivityOverlays is also governed by our Privacy Policy.</p>
          <p>
            If you disconnect your Strava account, we may delete or disassociate stored tokens and account data that
            we control, subject to legal or security retention obligations.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#111111]">6. Warranty Disclaimer</h2>
          <p>
            The service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, including implied
            warranties of merchantability, fitness for a particular purpose, and non-infringement.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-[#111111]">7. Contact</h2>
          <p>Email: shriniketh.d@gmail.com</p>
        </section>
      </article>
    </main>
  );
}
